name: knit-haskell
version: '0.8.0.0'
synopsis: a minimal Rmarkdown sort-of-thing for haskell, by way of Pandoc
description: ! 'knit-haskell is a beginning attempt at bringing some of the benefits
  of
  Rmarkdown to Haskell.
  It includes an effects stack
  (using <https://github.com/isovector/polysemy#readme polysemy> rather than mtl)
  which includes logging,
  a simplified interface to Pandoc and various writer-like effects to
  intersperse document building with regular code. Also included is
  a cache (in-memory and persisted to disk) to make caching results
  of long running computations simple. The cache provides tools for
  basic dependency tracking.
  Various helper functions are provided to simplify common operations,
  making it especially straightforward to build
  an HTML document from bits of markdown,
  latex and <http://hackage.haskell.org/package/lucid Lucid>
  or <http://hackage.haskell.org/package/blaze-html Blaze> html.
  Support is also included for including
  <http://hackage.haskell.org/package/hvega hvega> visualizations
  and diagrams from the <https://archives.haskell.org/projects.haskell.org/diagrams/
  diagrams>
  package.
  More information is available in the <https://github.com/adamConnerSax/knit-haskell/blob/master/Readme.md
  readme>.'
category: Text
author: Adam Conner-Sax
maintainer: adam_conner_sax@yahoo.com
copyright: 2019 Adam Conner-Sax
license: BSD3
github: adamConnerSax/knit-haskell
extra-source-files:
- ChangeLog.md
- Readme.md
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-unused-top-binds
  - -funbox-strict-fields
  - -fplugin=Polysemy.Plugin
#  - -fplugin=Fusion.Plugin
#  - -fdefer-type-errors
#  - -fno-warn-deferred-type-errors
  exposed-modules:
  - Knit.Effect.AtomicCache
  - Knit.Effect.Serialize
  - Knit.Effect.Logger
  - Knit.Effect.Docs
  - Knit.Effect.PandocMonad
  - Knit.Effect.Pandoc
  - Knit.Effect.UnusedId
  - Knit.Report
  - Knit.Report.Cache
  - Knit.Report.Input.Table.Colonnade
  - Knit.Report.Input.Html
  - Knit.Report.Input.Html.Lucid
  - Knit.Report.Input.Html.Blaze
  - Knit.Report.Input.Latex
  - Knit.Report.Input.MarkDown.PandocMarkDown
  - Knit.Report.Input.Visualization.Hvega
  - Knit.Report.Input.Visualization.Diagrams
  - Knit.Report.Output
  - Knit.Report.Output.Html
  - Knit.Report.Other.Lucid
  - Knit.Report.Other.Blaze
  - Knit.Utilities.Streamly
  dependencies:
  - aeson-pretty >=0.8.7 && <0.9
  - base >=4.12.0 && < 4.15
  - base64-bytestring >=1.0.0.2 && < 1.2
  - blaze-colonnade >=1.2.2 && < 1.3
  - bytestring >=0.10.8 && <0.11
  - case-insensitive >=1.2.0.11 && < 1.3
  - cereal >= 0.5.7 && < 0.6
  - colonnade >=1.1 && <1.3
  - containers >=0.5.0 && < 0.7
  - constraints >=0.10 && < 0.13
  - directory >=1.3.3.0 && <1.4.0.0
  - diagrams-lib >=1.4 && <1.5.0.0
  - diagrams-svg >=1.4.1 && <1.5.0.0
  - doctemplates >=0.2 && < 0.9
  - exceptions >= 0.10.0 && < 0.11
#  - fusion-plugin >= 0.2 && < 0.3.0
  - Glob >=0.10.0 && <0.11.0
  - http-client >=0.6.4 && <0.8
  - http-client-tls >=0.3.5.3 && <0.4
  - http-types >=0.12.3 && <0.13
  - lucid >=2.9.11 && <2.10
  - monad-control >= 1.0.2 && < 1.1
  - network >=2.8.0.0 && < 3.2
  - network-uri >=2.6.1.0 && < 2.8
  - text >=1.2.3 && <1.3
  - time >=1.8.0 && <2.0.0
  - random >=1.1 && <1.3
  - blaze-html >=0.9.1 && <0.10
  - hvega >= 0.2.0 && < 0.11
  - mtl >=2.2.2 && <2.3
  - pandoc >=2.7.2 && < 2.11
  - polysemy >= 1.3.0 && < 1.4
  - polysemy-plugin >= 0.2.0.0 && < 0.3
  - polysemy-zoo >= 0.6.0 && < 0.8
  - prettyprinter >=1.2.1 && < 1.7
  - say >= 0.1.0 && < 0.2
  - stm >= 2.4.5.1 && < 2.6
  - streamly >= 0.7.2 && <0.7.3
  - streamly-bytestring >= 0.1.0 && < 0.2
  - svg-builder >=0.1.1 && <0.2
  - transformers-base >= 0.4.5 && < 0.5
tests:
  Index:
    main: Index.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin
    dependencies:
    - base
    - containers
    - here
    - knit-haskell
    - polysemy
    - polysemy-plugin
    - text
  SimpleExample:
    main: SimpleExample.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin
    dependencies:
    - base
    - blaze-html
    - containers
    - here
    - hvega
    - knit-haskell
    - plots    
    - polysemy
    - polysemy-plugin
    - text
  MtlExample:
    main: MtlExample.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin
    dependencies:
    - base
    - blaze-html
    - containers
    - here
    - hvega
    - knit-haskell
    - mtl
    - polysemy
    - polysemy-plugin
    - text
  ErrorExample:
    main: ErrorExample.hs
    other-modules: []		
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin
    dependencies:
    - base
    - blaze-html
    - containers
    - here >=1.2.10 && <1.3.0
    - hvega
    - knit-haskell
    - polysemy
    - polysemy-plugin
    - text
  RandomExample:
    main: RandomExample.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin
    dependencies:
    - base
    - blaze-html
    - colonnade >= 1.2.0.2
    - containers
    - here >=1.2.10 && <1.3.0
    - hvega
    - knit-haskell
    - mtl >= 2.2.2
    - plots >=0.1.1.0 && <=0.2
    - polysemy
    - polysemy-plugin
    - polysemy-RandomFu >= 0.4.0 && < 0.5
    - random-fu >= 0.2.7.3 && < 0.3
    - random-source >= 0.3.0.6
    - text
  MultiDocExample:
    main: MultiDocExample.hs
    other-modules: []	    
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin
    dependencies:
    - base
    - blaze-html
    - containers
    - here >=1.2.10 && <1.3.0
    - hvega
    - knit-haskell
    - polysemy
    - polysemy-plugin
    - text
  AsyncExample:
    main: AsyncExample.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin -threaded
    dependencies:
    - base
    - blaze-html
    - containers
    - here
    - hvega
    - knit-haskell
    - plots    
    - polysemy
    - polysemy-plugin
    - text
  CacheExample:
    main: CacheExample.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin -threaded
    dependencies:
    - base
    - blaze-html
    - containers
    - here
    - hvega
    - knit-haskell
    - plots    
    - polysemy
    - polysemy-plugin
    - streamly
    - text
  CacheExample2:
    main: CacheExample2.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin -threaded
    dependencies:
    - base
    - blaze-html
    - bytestring
    - containers
    - here
    - hvega
    - knit-haskell
    - plots    
    - polysemy
    - polysemy-plugin
    - streamly
    - store
    - text    
data-dir: data
data-files:
- knit-haskell-templates/*.html
- knit-haskell-css/*.css
- pandoc-data/data/templates/*.html4
- pandoc-data/data/templates/*.html5
- pandoc-data/data/templates/default.latex
- pandoc-data/data/templates/default.markdown
- pandoc-data/data/templates/default.commonmark
- pandoc-data/data/templates/default.haddock
